[build]
  publish = "/"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Moon page redirect (new)
[[redirects]]
  from = "/moon/*"
  to = "/moon/:splat"
  status = 200

# Shitquiz-1 page redirect
[[redirects]]
  from = "/shitquiz-1/*"
  to = "/shitquiz-1/:splat"
  status = 200
  
# Shitquiz-2 page redirect
[[redirects]]
  from = "/shitquiz-2/*"
  to = "/shitquiz-2/:splat"
  status = 200


# Wilsonchat page redirect
[[redirects]]
  from = "/wilsonchat/*"
  to = "/wilsonchat/:splat"
  status = 200

# Rainforest page redirect
[[redirects]]
  from = "/rainforestsofcentralafrica/*"
  to = "/rainforestsofcentralafrica/:splat"
  status = 200

# Gandalf page redirect
[[redirects]]
  from = "/gandalf/*"
  to = "/gandalf/:splat"
  status = 200

 # Spwanchow page redirect
[[redirects]]
  from = "/spawnchow/*"
  to = "/spawnchow/:splat"
  status = 200

  # Maths page redirect
[[redirects]]
  from = "/maths/*"
  to = "/maths/:splat"
  status = 200

# Handle 404 errors (new)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
