[build]
  publish = "/"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Moon page redirect (new)
[[redirects]]
  from = "/moon/*"
  to = "/moon/:splat"
  status = 200

# Shitquiz-1 page redirect
[[redirects]]
  from = "/shitquiz-1/*"
  to = "/shitquiz-1/:splat"
  status = 200

# Handle 404 errors (new)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
